databases:
  - name: social-db
    databaseName: social
    user: social_user
    plan: free
    postgresMajorVersion: 16

  - name: keycloak-db
    databaseName: keycloak
    user: keycloak_user
    plan: free
    postgresMajorVersion: 16

services:
  - type: web
    name: keycloak
    env: docker
    repo: https://github.com/prasad7bhise/social-backend
    branch: master
    dockerfilePath: ./keycloak/Dockerfile
    plan: free
    autoDeploy: false
    healthCheckPath: /health/ready
    envVars:
      - key: PORT
        value: 8080
      - key: KEYCLOAK_ADMIN
        value: admin
      - key: KEYCLOAK_ADMIN_PASSWORD
        sync: false
      - key: KC_DB
        value: postgres
      - key: KC_DB_URL_HOST
        fromDatabase:
          name: keycloak-db
          property: host
      - key: KC_DB_URL_PORT
        fromDatabase:
          name: keycloak-db
          property: port
      - key: KC_DB_URL_DATABASE
        fromDatabase:
          name: keycloak-db
          property: database
      - key: KC_DB_USERNAME
        fromDatabase:
          name: keycloak-db
          property: user
      - key: KC_DB_PASSWORD
        fromDatabase:
          name: keycloak-db
          property: password
      - key: JAVA_OPTS_APPEND
        value: "-Xms128m -Xmx384m"

  - type: web
    name: social-backend
    env: docker
    repo: https://github.com/prasad7bhise/social-backend
    branch: master
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /api/auth/test
    envVars:
      - key: SPRING_PROFILES_ACTIVE
        value: postgres
      - key: DB_HOST
        fromDatabase:
          name: social-db
          property: host
      - key: DB_PORT
        fromDatabase:
          name: social-db
          property: port
      - key: DB_NAME
        fromDatabase:
          name: social-db
          property: database
      - key: DB_USERNAME
        fromDatabase:
          name: social-db
          property: user
      - key: DB_PASSWORD
        fromDatabase:
          name: social-db
          property: password
      - key: KEYCLOAK_ISSUER_URI
        value: https://keycloak-foj7.onrender.com/realms/social-realm
      - key: KEYCLOAK_SERVER_URL
        value: https://keycloak-foj7.onrender.com
      - key: KEYCLOAK_ADMIN_SECRET
        sync: false
      - key: CORS_ALLOWED_ORIGINS
        value: https://social-frontend.onrender.com

  - type: web
    name: social-frontend
    env: docker
    repo: https://github.com/prasad7bhise/social-frontend
    branch: master
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /
    envVars:
      - key: NEXTAUTH_URL
        value: https://social-frontend.onrender.com
      - key: NEXTAUTH_SECRET
        sync: false
      - key: KEYCLOAK_CLIENT_ID
        value: social-frontend
      - key: KEYCLOAK_ISSUER
        value: https://keycloak-foj7.onrender.com/realms/social-realm
      - key: NEXT_PUBLIC_API_BASE_URL
        value: https://social-backend.onrender.com
