spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 50MB
      max-request-size: 100MB

  datasource:
    url: jdbc:mysql://localhost:3306/social?allowPublicKeyRetrieval=true&useSSL=false
    username: social
    password: socialPass123!
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:liquibase/changelog-master.xml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8081/realms/social-realm
app:
  upload:
    dir: uploads

  keycloak:
    admin:
      server-url: http://localhost:8081
      realm: social-realm
      client-id: social-backend-admin
      client-secret: "z1rsgl4XOSflnpKbtCqDcdaB3PuUgTfx"

server:
  port: 8080
  tomcat:
    threads:
      max: 50
      min-spare: 5
    max-connections: 100
    accept-count: 10

cors:
  allowed-origins: http://localhost:3000
